apiVersion: v1
kind: Service
metadata:
  name: gowebapp-service
  labels:
    app: gowebapp-service
spec:
  selector:
    app: webapp
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort
